title: MyPartyPix

description: >
  Fun . Loving . Memory
url:

# Build settings
markdown: kramdown
theme: minima
gems:

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

collections:
  video:
    output: true
    permalink: /reel/:path/
