- title: "Photobooth Rental"
  description: "Complete setup with two friendly crew!"
  image: ""

- title: "Party Needs"
  description: "Party Decor, Food "
  image: "Party Decor, Food Carts, Photo and Video, Facepaint, Dessert/candy Buffet"

- title: "Other Services"
  description: "Flipbook, Hashtag instagram photo print, Photoman"
  image: ""
