- title: "Photobooth Rental"
  description: "Complete setup with two friendly crew!"
  image: "sample-service.jpg"

- title: "Party Needs"
  description: "Party Decor, Food "
  image: "sample-service.jpg"

- title: "Other Services"
  description: "Flipbook, Hashtag instagram photo print, Photoman"
  image: "sample-service.jpg"
